//Adding Comments: Choose two of the programs you’ve written, and add at least one comment to each. If you don’t have anything specific to write because your programs are too simple at this point, just add your name and the current date at the top of each program file. Then write one sentence describing what the program does.

// Define the area in sqft of a plot
let areaSyard: number = 120;

// Calculate the area in sqft of the sq yards using the formula sq yard * 9
let areaSft: number = areaSyard * 9 ;

// Print the calculated area in sqft
console.log("The area of the Plot is:", areaSft);

///////////////////////////////////////////////////////////////

// Define when and who was solving exercise no 10
let student: string = "Salman Sattar";
let currentDate: Date = new Date();

// Print the detail
console.log(`The Exercise No 10 is written by ${student} on dated ${currentDate}`);
